Guard colorNames variable under SK_SUPPORT_UNITTEST.
That way clang does not complain with unneeded-internal-declaration warning,
because otherwise to clang this variable is unused and thus it won't
emit code for it.

The warning is:
../../src/utils/SkParseColor.cpp:35:3: error: variable 'colorNames' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
} colorNames[] = {

R=bsalomon@google.com, robertphillips@google.com

Author: tfarina@chromium.org

Review URL: https://codereview.chromium.org/27229004

git-svn-id: http://skia.googlecode.com/svn/trunk@11798 2bbb7eff-a529-9590-31e7-b0007b416f81